app.port=8181
app.openhab.baseUrl=http://192.168.0.34:8080/rest/
app.electricity.oteUrl=https://www.ote-cr.cz/cs/kratkodobe-trhy/elektrina/denni-trh?date=
server.port=${app.port}
#logging
logging.level.root=WARN
logging.level.com.hyblerm.homecontroller=DEBUG
logging.file.name=home-portal.log
#spring boot admin
spring.boot.admin.client.url=http://127.0.0.1:${app.port}
management.endpoints.web.exposure.include=*
#db
spring.datasource.url=jdbc:h2:file:/tmp/data/demo
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto = create


