app.port=8181
app.openhab.baseUrl=http://192.168.0.34:8080/rest/
app.electricity.oteUrl=https://www.ote-cr.cz/cs/kratkodobe-trhy/elektrina/denni-trh?date=
app.nicehash.l3PlusIncomeUrl=https://www.google.com/search?q=nicehash+l3%2B+income&oq=nicehash+l3%2B+income&aqs=chrome..69i57j0i19i512l2j0i19i22i30l4j69i60.6319j0j4&sourceid=chrome&ie=UTF-8
server.port=${app.port}
#logging
logging.level.root=WARN
logging.level.com.hyblerm.homecontroller=DEBUG
logging.file.name=home-portal.log
#spring boot admin
spring.boot.admin.client.url=http://127.0.0.1:${app.port}
management.endpoints.web.exposure.include=*
#db
spring.datasource.url=jdbc:h2:file:/tmp/data/demo
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto = create


