app.port=8181
app.openhab.baseUrl=http://192.168.0.34:8080/rest/
server.port=${app.port}
logging.level.root=WARN
logging.level.com.hyblerm.homecontroller=DEBUG
spring.boot.admin.client.url=http://127.0.0.1:${app.port}
management.endpoints.web.exposure.include=*
logging.file.name=home-portal.log

