#!/usr/bin/env bash
# Deploy OpenHAB config from this monorepo to the live OpenHAB host.
#
# Dry-run by default. Pass --apply to actually write to the server.
#
#   ./scripts/deploy-openhab.sh            # show what would change
#   ./scripts/deploy-openhab.sh --apply    # do it
#
# Why rsync and not the old `git reset --hard`: the server had untracked
# live config (items/atmos.items) and locally-upgraded jrule jars. A hard
# reset deletes the first and downgrades the second. rsync without
# --delete only adds and updates, so server-side drift survives and shows
# up in the dry-run instead of being silently destroyed.
set -euo pipefail

HOST="${OPENHAB_HOST:-192.168.1.109}"
USER="${OPENHAB_USER:-dev}"
DEST="${OPENHAB_DIR:-/etc/openhab}"
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/openhab-ruprechtice"

APPLY=""
[ "${1:-}" = "--apply" ] && APPLY=1

RSYNC_ARGS=(
  -rlptv
  --exclude '.git/'
  --exclude '.idea/'
  --exclude 'automation/jrule/gen/'   # regenerated by JRule on the server
)
[ -n "${APPLY}" ] || RSYNC_ARGS+=(--dry-run)

echo "==> ${SRC}/  ->  ${USER}@${HOST}:${DEST}/"
[ -n "${APPLY}" ] || echo "==> DRY RUN (pass --apply to write)"

rsync "${RSYNC_ARGS[@]}" "${SRC}/" "${USER}@${HOST}:${DEST}/"

if [ -n "${APPLY}" ]; then
  echo "==> OpenHAB picks up items/things/rules changes automatically; no restart needed."
  echo "==> Watch it apply:  ./scripts/logs.sh openhab"
else
  echo "==> Nothing was written."
fi
